# Attention:
# Use this docker-compose to:
# - Up development environment: docker-compose up
# - Build docker images: docker-compose build

version: '3.6'

services:
  database:
      image: postgres
      ports:
        - 5432:5432
      networks:
        - default
        - bothub
      environment:
        - POSTGRES_USER=${POSTGRES_USER:-bothub}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-bothub}
        - POSTGRES_DB=${POSTGRES_DB:-bothub}
  bothub:
    image: ${DOCKER_IMAGE_NAME:-ilha/bothub}:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - default
      - bothub
    environment:
      - SECRET_KEY=${SECRET_KEY:-SK}
      - DEBUG=${DEBUG:-true}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - DEFAULT_DATABASE=${DEFAULT_DATABASE:-postgres://bothub:bothub@database:5432/bothub}
      - LANGUAGE_CODE=${LANGUAGE_CODE:-en-us}
      - TIME_ZONE=${TIME_ZONE:-UTC}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT:-25}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-webmaster@localhost}
      - SERVER_EMAIL=${SERVER_EMAIL:-root@localhost}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL:-false}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-false}
      - ADMINS=${ADMINS}
      - CSRF_COOKIE_DOMAIN=${CSRF_COOKIE_DOMAIN}
      - CSRF_COOKIE_SECURE=${CSRF_COOKIE_SECURE:-false}
      - BOTHUB_WEBAPP_BASE_URL=${BOTHUB_WEBAPP_BASE_URL:-http://localhost/}
      - BOTHUB_NLP_BASE_URL=${BOTHUB_NLP_BASE_URL:-http://bothub-nlp-api:2657/}
      - CHECK_ACCESSIBLE_API_URL=${CHECK_ACCESSIBLE_API_URL}
      - SEND_EMAILS=${SEND_EMAILS:-true}
      - SUPPORTED_LANGUAGES=${SUPPORTED_LANGUAGES:-en|pt}


networks:
  bothub:
    external: true
